Resources:
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: MyRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service:
                - "ec2.amazonaws.com"
  MyFullAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: MyFullAccessPolicy
      PolicyDocument:
        Statement:
          - Sid: MyRoleStmt
            Effect: Allow
            Action: "*"
            Resource: "*"
      Roles:
        - Ref: MyRole

Outputs:
  MyRoleName:
    Description: The name of My Role
    Value:
      Ref: MyRole
    Export:
      Name: MyRole:NAME
